---
stages:
- test
- integration
condor:
  before_script:
  - source scripts/set-voldir.sh runtests
  - source scripts/init-env.sh
  - cp -R runtests* test $VOLDIR
  - cd $VOLDIR
  script:
  - ./runtests.py --interp generic --interp_path true --executor condor --batch_size 1 --condor_log --condor_log_all --db postgres --db_pg_schema runtests test/samples/
  - condor_wait -status -echo job_*_condor_*.log
  after_script:
  - scripts/clean-voldir.sh runtests
  cache:
    key: all
    paths:
    - env/
  stage: integration
  tags:
  - condor
  except:
  - triggers

git-sync:
  before_script:
  - eval `ssh-agent`
  - echo "$PUSH_KEY" | ssh-add -
  script:
  - git sync-remote git@github.com:edgemaster/runtests.git git@gitlab.doc.ic.ac.uk:tw1509/runtests.git
  - ssh-agent -k
  only:
  - triggers
